### ISSUE TITLE
Can we use this solution for activemq?

### ISSUE THREAD

**Issue by KrishnaPrasanthVemuganti** [mizrael/WebApiWithBackgroundWorker#2]
Thank you for the implementation. I am looking into implementation for activemqs.... can this be used for activemqs as well?

**Comment by mizrael** [comment]
hi @KrishnaPrasanthVemuganti, thanks for reaching out! Yes, of course, you can totally use it with ActiveMQ, just implement the interface _ISubscriber_ and register it instead of _RabbitSubscriber_ and you're done. Then of course you'll have to take care of the publisher.

**Comment by KrishnaPrasanthVemuganti** [comment]
Thank you @mizrael  for the effort i have ported this to activemq.... 🙂

**Comment by mizrael** [comment]
great job!
