### ISSUE TITLE
Coding

### ISSUE THREAD

**Issue by boukenka** [mizrael/WebApiWithBackgroundWorker#3]
Hello @mizrael,

Thank you for your blog and your coding! They are very useful. I just have a few comments.

In the RabbitSubscriber class, in the _OnMessageReceivedAsync_ method, the following modification could be made?

```
await this.OnMessage(this, new RabbitSubscriberEventArgs(message));
```
replaced by :
```
await OnMessage.Invoke(this, new RabbitSubscriberEventArgs(message));
```

Exceptions can also be written as follows in the Consumer class :
```
catch (OperationCanceledException)
```

Finally, it is not necessary to have this line of code :
```
private static readonly Random Random = new Random()
```

I hope my comments are Ok. Happy coding 😄 

PS : Blazor is fantastic !

**Comment by mizrael** [comment]
Hi!
Thank you for the suggestions! I take a look at the code and get back to
you.

Cheers!
